/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiRouteImport } from './routes/ui'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as BoxesIndexRouteImport } from './routes/boxes/index'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as BoxesBaseRouteImport } from './routes/boxes/$base'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppsNewRouteImport } from './routes/apps_.new'
import { Route as OrgsSlugSettingsRouteImport } from './routes/orgs/$slug.settings'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as BoxesBaseAppsAppRouteImport } from './routes/boxes/$base_.apps.$app'

const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesIndexRoute = BoxesIndexRouteImport.update({
  id: '/boxes/',
  path: '/boxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesBaseRoute = BoxesBaseRouteImport.update({
  id: '/boxes/$base',
  path: '/boxes/$base',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsNewRoute = AppsNewRouteImport.update({
  id: '/apps_/new',
  path: '/apps/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsSlugSettingsRoute = OrgsSlugSettingsRouteImport.update({
  id: '/orgs/$slug/settings',
  path: '/orgs/$slug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesBaseAppsAppRoute = BoxesBaseAppsAppRouteImport.update({
  id: '/boxes/$base_/apps/$app',
  path: '/boxes/$base/apps/$app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/ui': typeof UiRoute
  '/apps/new': typeof AppsNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boxes/$base': typeof BoxesBaseRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/boxes/': typeof BoxesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/orgs/$slug/settings': typeof OrgsSlugSettingsRoute
  '/boxes/$base/apps/$app': typeof BoxesBaseAppsAppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/ui': typeof UiRoute
  '/apps/new': typeof AppsNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boxes/$base': typeof BoxesBaseRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/boxes': typeof BoxesIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/orgs/$slug/settings': typeof OrgsSlugSettingsRoute
  '/boxes/$base/apps/$app': typeof BoxesBaseAppsAppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/domains': typeof DomainsRoute
  '/login': typeof LoginRoute
  '/ui': typeof UiRoute
  '/apps_/new': typeof AppsNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/boxes/$base': typeof BoxesBaseRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/boxes/': typeof BoxesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/orgs/$slug/settings': typeof OrgsSlugSettingsRoute
  '/boxes/$base_/apps/$app': typeof BoxesBaseAppsAppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/domains'
    | '/login'
    | '/ui'
    | '/apps/new'
    | '/auth/callback'
    | '/boxes/$base'
    | '/docs/$slug'
    | '/boxes/'
    | '/docs/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/orgs/$slug/settings'
    | '/boxes/$base/apps/$app'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/domains'
    | '/login'
    | '/ui'
    | '/apps/new'
    | '/auth/callback'
    | '/boxes/$base'
    | '/docs/$slug'
    | '/boxes'
    | '/docs'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/orgs/$slug/settings'
    | '/boxes/$base/apps/$app'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/domains'
    | '/login'
    | '/ui'
    | '/apps_/new'
    | '/auth/callback'
    | '/boxes/$base'
    | '/docs/$slug'
    | '/boxes/'
    | '/docs/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
    | '/orgs/$slug/settings'
    | '/boxes/$base_/apps/$app'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  DomainsRoute: typeof DomainsRoute
  LoginRoute: typeof LoginRoute
  UiRoute: typeof UiRoute
  AppsNewRoute: typeof AppsNewRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BoxesBaseRoute: typeof BoxesBaseRoute
  DocsSlugRoute: typeof DocsSlugRoute
  BoxesIndexRoute: typeof BoxesIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  OrgsSlugSettingsRoute: typeof OrgsSlugSettingsRoute
  BoxesBaseAppsAppRoute: typeof BoxesBaseAppsAppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/': {
      id: '/boxes/'
      path: '/boxes'
      fullPath: '/boxes/'
      preLoaderRoute: typeof BoxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/$base': {
      id: '/boxes/$base'
      path: '/boxes/$base'
      fullPath: '/boxes/$base'
      preLoaderRoute: typeof BoxesBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps_/new': {
      id: '/apps_/new'
      path: '/apps/new'
      fullPath: '/apps/new'
      preLoaderRoute: typeof AppsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$slug/settings': {
      id: '/orgs/$slug/settings'
      path: '/orgs/$slug/settings'
      fullPath: '/orgs/$slug/settings'
      preLoaderRoute: typeof OrgsSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/$base_/apps/$app': {
      id: '/boxes/$base_/apps/$app'
      path: '/boxes/$base/apps/$app'
      fullPath: '/boxes/$base/apps/$app'
      preLoaderRoute: typeof BoxesBaseAppsAppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  DomainsRoute: DomainsRoute,
  LoginRoute: LoginRoute,
  UiRoute: UiRoute,
  AppsNewRoute: AppsNewRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BoxesBaseRoute: BoxesBaseRoute,
  DocsSlugRoute: DocsSlugRoute,
  BoxesIndexRoute: BoxesIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  OrgsSlugSettingsRoute: OrgsSlugSettingsRoute,
  BoxesBaseAppsAppRoute: BoxesBaseAppsAppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
